[included]
"androidx.activity:activity" = "[AndroidX Activity](https://developer.android.com/jetpack/androidx/releases/activity#{})"
"androidx.activity:activity-compose" = "[AndroidX Activity Compose](https://developer.android.com/jetpack/androidx/releases/activity#{})"
"androidx.annotation:annotation" = "[AndroidX Annotation](https://developer.android.com/jetpack/androidx/releases/annotation#{})"
"androidx.appcompat:appcompat" = "[AndroidX Appcompat](https://developer.android.com/jetpack/androidx/releases/appcompat#{})"
"androidx.autofill:autofill" = "[AndroidX Autofill](https://developer.android.com/jetpack/androidx/releases/autofill#{})"
"androidx.browser:browser" = "[AndroidX Browser](https://developer.android.com/jetpack/androidx/releases/browser#{})"
"androidx.core:core-ktx" = "[AndroidX Core](https://developer.android.com/jetpack/androidx/releases/core#{})"
"androidx.compose.compiler:compiler" = "[AndroidX Compose Compiler](https://developer.android.com/jetpack/androidx/releases/compose-compiler#{})"
"androidx.compose:compose-bom" = "[AndroidX Compose BoM](https://developer.android.com/develop/ui/compose/bom/bom-mapping)"
"androidx.compose.material3:material3" = "[AndroidX Compose Material](https://developer.android.com/jetpack/androidx/releases/compose-material3#{})"
"androidx.constraintlayout:constraintlayout" = "[AndroidX ConstraintLayout](https://developer.android.com/jetpack/androidx/releases/constraintlayout#constraintlayout-{})"
"androidx.constraintlayout:constraintlayout-compose" = "[AndroidX ConstraintLayout Compose](https://developer.android.com/jetpack/androidx/releases/constraintlayout#{})"
"androidx.fragment:fragment-ktx" = "[AndroidX Fragment](https://developer.android.com/jetpack/androidx/releases/fragment#{})"
"androidx.lifecycle:lifecycle-runtime-ktx" = "[AndroidX Lifecycle Runtime](https://developer.android.com/jetpack/androidx/releases/lifecycle#{})"
"androidx.lifecycle:lifecycle-viewmodel-compose" = "[AndroidX Lifecycle ViewModel Compose](https://developer.android.com/jetpack/androidx/releases/lifecycle#{})"
"androidx.lifecycle:lifecycle-viewmodel-ktx" = "[AndroidX Lifecycle ViewModel](https://developer.android.com/jetpack/androidx/releases/lifecycle#{})"
"androidx.lifecycle:lifecycle-service" = "[AndroidX Lifecycle Service](https://developer.android.com/jetpack/androidx/releases/lifecycle#{})"
"androidx.navigation3:navigation3-runtime" = "[AndroidX Navigation3](https://developer.android.com/jetpack/androidx/releases/navigation3#{})"
"androidx.recyclerview:recyclerview" = "[AndroidX RecyclerView](https://developer.android.com/jetpack/androidx/releases/recyclerview#{})"
"androidx.startup:startup-runtime" = "[AndroidX Startup](https://developer.android.com/jetpack/androidx/releases/startup#{})"
"app.cash.paykit:core" = "[CashApp Pay](https://github.com/cashapp/cash-app-pay-android-sdk/releases/tag/v{})"
"ch.twint.payment.sdk:android-sdk" = "[TWINT](https://docs.adyen.com/payment-methods/twint)"
"com.adyen.threeds:adyen-3ds2" = "[Adyen 3DS2](https://github.com/Adyen/adyen-3ds2-android/releases/tag/{})"
"com.android.tools.build:gradle" = "[Android Gradle Plugin](https://developer.android.com/build/releases/gradle-plugin)"
"com.google.android.gms:play-services-wallet" = "[Play Services Wallet](https://developers.google.com/pay/api/android/support/release-notes)"
"com.google.android.material:material" = "[Material](https://github.com/material-components/material-components-android/releases/tag/{})"
"com.squareup.okhttp3:okhttp" = "[OkHttp](https://square.github.io/okhttp/changelogs/changelog/)"
"com.tencent.mm.opensdk:wechat-sdk-android-without-mta" = "[WeChat](https://developers.weixin.qq.com/doc/oplatform/en/Mobile_App/Access_Guide/Android.html)"
"kotlin" = "[Kotlin](https://github.com/JetBrains/kotlin/releases/tag/v{})"
"org.jetbrains.kotlinx:kotlinx-coroutines-android" = "[Kotlin Coroutines Android](https://github.com/Kotlin/kotlinx.coroutines/releases/tag/{})"
"org.jetbrains.kotlinx:kotlinx-coroutines-core" = "[Kotlin Coroutines](https://github.com/Kotlin/kotlinx.coroutines/releases/tag/{})"
"org.jetbrains.kotlinx:kotlinx-coroutines-play-services" = "[Kotlin Coroutines Play Services](https://github.com/Kotlin/kotlinx.coroutines/releases/tag/{})"

[excluded]
# We only need the package name, but since toml files are key value base we set an empty value.
"androidx.arch.core:core-testing" = ""
"androidx.compose.material:material-icons-core" = ""
"androidx.compose.ui:ui" = ""
"androidx.compose.ui:ui-graphics" = ""
"androidx.compose.ui:ui-test-manifest" = ""
"androidx.compose.ui:ui-tooling" = ""
"androidx.compose.ui:ui-tooling-preview" = ""
"androidx.hilt:hilt-navigation-compose" = ""
# This dependency is already defined by another
"androidx.navigation3:navigation3-ui" = ""
"androidx.preference:preference-ktx" = ""
"androidx.test.espresso:espresso-contrib" = ""
"androidx.test.espresso:espresso-core" = ""
"androidx.test.espresso:espresso-intents" = ""
"androidx.test.ext:junit" = ""
"androidx.test.ext:junit-ktx" = ""
"androidx.test.uiautomator:uiautomator" = ""
"androidx.test:rules" = ""
"app.cash.turbine:turbine" = ""
"checkout.android.library" = ""
"checkout.dependency.list.aggregate" = ""
"checkout.dependency.list.generate" = ""
"checkout.dependency.resolve" = ""
"checkout.detekt" = ""
"checkout.dokka" = ""
"checkout.jacoco" = ""
"checkout.ktlint" = ""
"checkout.publish" = ""
"checkout.sonar" = ""
"com.adevinta.android:barista" = ""
"com.android.application" = ""
"com.android.library" = ""
"com.android.tools.lint:lint" = ""
"com.android.tools.lint:lint-api" = ""
"com.android.tools.lint:lint-tests" = ""
"com.google.dagger.hilt.android" = ""
"com.google.dagger:hilt-android" = ""
"com.google.dagger:hilt-android-compiler" = ""
"com.google.dagger:hilt-android-testing" = ""
"com.google.dagger:hilt-compiler" = ""
"com.google.devtools.ksp" = ""
"com.lemonappdev:konsist" = ""
"com.pinterest.ktlint:ktlint-cli" = ""
"com.squareup.leakcanary:leakcanary-android" = ""
"com.squareup.moshi:moshi-adapters" = ""
"com.squareup.moshi:moshi-kotlin" = ""
"com.squareup.okhttp3:logging-interceptor" = ""
"com.squareup.okhttp3:mockwebserver" = ""
"com.squareup.retrofit2:converter-moshi" = ""
"com.squareup.retrofit2:retrofit" = ""
"io.gitlab.arturbosch.detekt" = ""
"io.gitlab.arturbosch.detekt:detekt-formatting" = ""
"io.gitlab.arturbosch.detekt:io.gitlab.arturbosch.detekt.gradle.plugin" = ""
"junit:junit" = ""
"org.bitbucket.b_c:jose4j" = ""
"org.jetbrains.dokka" = ""
"org.jetbrains.dokka:dokka-gradle-plugin" = ""
"org.jetbrains.kotlin.plugin.serialization" = ""
"org.jetbrains.kotlinx.binary-compatibility-validator" = ""
"org.jetbrains.kotlinx:kotlinx-coroutines-test" = ""
"org.json:json" = ""
"org.junit.jupiter:junit-jupiter-api" = ""
"org.junit.jupiter:junit-jupiter-engine" = ""
"org.junit.jupiter:junit-jupiter-params" = ""
"org.junit.platform:junit-platform-launcher" = ""
"org.junit.vintage:junit-vintage-engine" = ""
"org.mockito.kotlin:mockito-kotlin" = ""
"org.mockito:mockito-android" = ""
"org.mockito:mockito-junit-jupiter" = ""
"org.robolectric:robolectric" = ""
"org.sonarqube" = ""
"org.sonarqube:org.sonarqube.gradle.plugin" = ""
"resolve-dependencies" = ""
"sonarqube-convention" = ""
# These are used in our SDK, but we already display Kotlin in through another dependency.
"kotlin-android" = ""
"kotlin-parcelize" = ""
"org.jetbrains.kotlin.android" = ""
"org.jetbrains.kotlin:kotlin-gradle-plugin" = ""
"org.jetbrains.kotlin:kotlin-parcelize-runtime" = ""
"org.jetbrains.kotlin.plugin.compose" = ""
