[versions]
# SDK
compile-sdk = "36"
target-sdk = "36"
min-sdk = "23"

# App version, only used for example app, no need to increment
version-code = "1"

# Build script
android-gradle-plugin = "8.13.2"
kotlin = "2.3.0"
ksp = "2.3.5"
dokka = "2.1.0"
hilt = "2.58"

# Code quality
detekt = "1.23.8"
jacoco = "0.8.12"
ktlint = "1.5.0"
sonarqube = "7.2.2.6593"
binary-compatibility-validator = "0.18.1"

# Android dependencies
activity = "1.12.4"
annotation = "1.9.1"
appcompat = "1.7.1"
autofill = "1.3.0"
browser = "1.9.0"
coroutines = "1.10.2"
fragment = "1.8.9"
lifecycle = "2.10.0"
material = "1.13.0"
material3 = "1.5.0-alpha13"
navigation3 = "1.0.0"
recyclerview = "1.4.0"
startup = "1.2.0"
constraintlayout = "2.2.1"
constraintlayout-compose = "1.1.1"

# Compose dependencies
compose-activity = "1.12.3"
compose-bom = "2025.12.01"
compose-hilt = "1.3.0"
compose-viewmodel = "2.10.0"

# Adyen dependencies
adyen3ds2 = "2.2.25"

# External dependencies
cash-app-pay = "2.5.0"
okhttp = "4.12.0"
play-services-wallet = "19.5.0"
twint = "8.0.0"
wechat-pay = "6.8.0"

# Example app
leak-canary = "2.14"
moshi-adapters = "1.15.2"
moshi-kotlin-adapter = "1.15.2"
okhttp-logging = "4.12.0"
preference = "1.2.1"
retrofit2 = "2.12.0"

# Tests
arch-core-testing = "2.2.0"
barista = "4.3.0"
espresso = "3.7.0"
json = "20250107"
jose4j = "0.9.6"
junit-jupiter = "5.14.2"
konsist = "0.17.3"
lint = "31.13.2"
mockito-kotlin = "5.4.0"
mockito = "5.21.0"
robolectric = "4.16.1"
test-ext = "1.3.0"
test-rules = "1.7.0"
turbine = "1.2.1"
uiautomator = "2.3.0"
core-ktx = "1.17.0"
junit = "4.13.2"
junit-version = "1.3.0"

[libraries]

# Production libraries
adyen3ds2 = { group = "com.adyen.threeds", name = "adyen-3ds2", version.ref = "adyen3ds2" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-autofill = { group = "androidx.autofill", name = "autofill", version.ref = "autofill" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout-compose" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycle" }
androidx-navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3" }
androidx-preference = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }
cash-app-pay = { group = "app.cash.paykit", name = "core", version.ref = "cash-app-pay" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-hilt = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "compose-hilt" }
compose-material = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-core" }
compose-ui-main = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "compose-viewmodel" }
google-pay-play-services-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-play-services", version.ref = "coroutines" }
google-pay-play-services-wallet = { group = "com.google.android.gms", name = "play-services-wallet", version.ref = "play-services-wallet" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
leak-canary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leak-canary" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshi-adapters" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi-kotlin-adapter" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp-logging" }
parcelize = { group = "org.jetbrains.kotlin", name = "kotlin-parcelize-runtime", version.ref = "kotlin" }
retrofit-main = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit2" }
wechat = { group = "com.tencent.mm.opensdk", name = "wechat-sdk-android-without-mta", version.ref = "wechat-pay" }
detekt = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
ktlint-cli = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlint" }
twint = { group = "ch.twint.payment.sdk", name = "android-sdk", version.ref = "twint" }

# Test libraries
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "test-rules" }
androidx-test-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "test-ext" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-test-lifecycle = { group = "androidx.arch.core", name = "core-testing", version.ref = "arch-core-testing" }
barista = { group = "com.adevinta.android", name = "barista", version.ref = "barista" }
espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espresso" }
hilt-test = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler-test = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
jose4j = { group = "org.bitbucket.b_c", name = "jose4j", version.ref = "jose4j" }
json = { group = "org.json", name = "json", version.ref = "json" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit-jupiter" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit-jupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit-jupiter" }
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
junit-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit-jupiter" }
konsist = { group = "com.lemonappdev", name = "konsist", version.ref = "konsist" }
kotlinx-test-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
cash-app-turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
lint = { group = "com.android.tools.lint", name = "lint", version.ref = "lint" }
lint-api = { group = "com.android.tools.lint", name = "lint-api", version.ref = "lint" }
lint-tests = { group = "com.android.tools.lint", name = "lint-tests", version.ref = "lint" }
mockito-junit-jupiter = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
mockito-android-main = { group = "org.mockito", name = "mockito-android", version.ref = "mockito" }
mock-web-server = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }

# Util libraries
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-plugin" }
detekt-gradle-plugin = { group = "io.gitlab.arturbosch.detekt", name = "io.gitlab.arturbosch.detekt.gradle.plugin", version.ref = "detekt" }
dokka-gradle-plugin = { group = "org.jetbrains.dokka", name = "dokka-gradle-plugin", version.ref = "dokka" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
sonarqube-gradle-plugin = { group = "org.sonarqube", name = "org.sonarqube.gradle.plugin", version.ref = "sonarqube" }

[bundles]

# Production bundles
androidx-lifecycle = ["androidx-lifecycle-runtime", "androidx-lifecycle-viewmodel-ktx", "androidx-lifecycle-service"]
androidx-navigation3 = ["androidx-navigation3-runtime", "androidx-navigation3-ui"]
compose-ui = ["compose-ui-main", "compose-ui-graphics", "compose-ui-tooling-preview"]
kotlin-coroutines = ["kotlin-coroutines-core", "kotlin-coroutines-android"]
moshi = ["moshi-adapters", "moshi-kotlin"]
retrofit = ["retrofit-main", "retrofit-converter-moshi"]

# Test bundles
androidx-test = ["androidx-test-rules", "androidx-test-junit-ktx", "androidx-test-uiautomator"]
espresso = ["espresso-contrib", "espresso-core", "espresso-intents"]
junit = ["junit-jupiter-api", "junit-jupiter-engine", "junit-launcher", "junit-jupiter-params", "junit-vintage-engine"]
kotlin-coroutines-test = ["kotlinx-test-coroutines", "cash-app-turbine"]
mockito = ["mockito-junit-jupiter", "mockito-kotlin"]
mockito-android = ["mockito-android-main", "mockito-kotlin"]

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-parcelize = { id = "kotlin-parcelize" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
jacoco = { id = "jacoco" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }

# Plugins defined by this project
checkout-android-library = { id = "checkout.android.library" }
checkout-detekt = { id = "checkout.detekt" }
checkout-dokka = { id = "checkout.dokka" }
checkout-jacoco = { id = "checkout.jacoco" }
checkout-ktlint = { id = "checkout.ktlint" }
checkout-publish = { id = "checkout.publish" }
checkout-sonar = { id = "checkout.sonar" }
dependency-list-aggregate = { id = "checkout.dependency.list.aggregate" }
dependency-list-generate = { id = "checkout.dependency.list.generate" }
dependency-resolve = { id = "checkout.dependency.resolve" }
